### ISSUE TITLE
delete this repo?

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/files#3]
there are no files on here,and it just clutter in the Wurst-Imperium organization

**Comment by Alexander01998** [comment]
There are plenty of files here.
This repo contains everything that can be downloaded on https://www.wurst-client.tk/downloads/ except for the Wurst Client itself.

**Comment by pokeball99** [comment]
um..... well then this must be a mirage,right?
![image](https://cloud.githubusercontent.com/assets/9436061/9366715/7ec7c746-467e-11e5-839a-d529b0e337f8.png)

**Comment by Alexander01998** [comment]
Rather a poor eyesight:

![Where the files hide](https://cloud.githubusercontent.com/assets/10100202/9366779/ac29cbea-46b9-11e5-9b78-e89f999f0e9e.png)
